# Generated by Django 4.2.6 on 2023-10-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("authors", models.TextField()),
                ("publication_date", models.DateField()),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="book_covers/")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("popularity", models.IntegerField(default=0)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("EDUCATIONAL", "EDUCATIONAL"),
                            ("SELFHELP", "SELFHELP"),
                            ("NOVELS", "NOVELS"),
                            ("FINANCE", "FINANCE"),
                            ("COMICS", "COMICS"),
                            ("UNCATEGORISE", "UNCATEGORISE"),
                        ],
                        default="UNCATEGORISED",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
