# Generated by Django 4.2.6 on 2023-10-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="is_ordered",
            field=models.BooleanField(default=False),
        ),
    ]
